name: two_m_production
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  cloud_firestore: ^6.1.1
  dartz: ^0.10.1
  device_preview: ^1.2.0
  easy_localization: ^3.0.8
  firebase_auth: ^6.1.1
  firebase_core: ^4.3.0
  flutter:
    sdk: flutter
  fl_chart: ^0.70.2
  flutter_bloc: ^9.1.0
  flutter_native_contact_picker_plus: ^1.3.1
  permission_handler: ^11.0.0
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.0.9
  gap: ^3.0.1
  get_it: ^9.2.0
  go_router: ^16.2.1
  image_picker: ^1.2.0
  intl: ^0.20.2
  lottie: ^3.3.2
  photo_view: ^0.15.0
  shared_preferences: ^2.5.4
  smooth_page_indicator: ^1.2.1
  carousel_slider: ^5.1.1
  connectivity_plus: ^7.0.0
  local_auth: ^3.0.1
dev_dependencies:
  build_runner: ^2.10.4
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  mockito: ^5.6.1
flutter_native_splash:
  color: "#FFe64a19" # شفاف تمامًا
  image: null # مفيش صورة

  android_12:
    color: "#FFe64a19"
    image: null

  fullscreen: true
flutter:
  uses-material-design: true
  assets:
    - assets/image/
    - assets/icon/
    - assets/lottie/
    - assets/translations/
  fonts:
    # ===================== Arabic Font =====================
    - family: Tajawal
      fonts:
        - asset: assets/fonts/arabic/Tajawal-Light.ttf
          weight: 300
        - asset: assets/fonts/arabic/Tajawal-Regular.ttf
          weight: 400
        - asset: assets/fonts/arabic/Tajawal-Medium.ttf
          weight: 500
        - asset: assets/fonts/arabic/Tajawal-Bold.ttf
          weight: 700
        - asset: assets/fonts/arabic/Tajawal-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/arabic/Tajawal-Black.ttf
          weight: 900

    # ===================== English Mono Font =====================
    - family: RobotoMono
      fonts:
        - asset: assets/fonts/english/RobotoMono-Thin.ttf
          weight: 100
        - asset: assets/fonts/english/RobotoMono-Light.ttf
          weight: 300
        - asset: assets/fonts/english/RobotoMono-Regular.ttf
          weight: 400
        - asset: assets/fonts/english/RobotoMono-Medium.ttf
          weight: 500
        - asset: assets/fonts/english/RobotoMono-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/english/RobotoMono-Bold.ttf
          weight: 700
        - asset: assets/fonts/english/RobotoMono-Italic.ttf
          style: italic
        - asset: assets/fonts/english/RobotoMono-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/english/RobotoMono-BoldItalic.ttf
          weight: 700
          style: italic

    # ===================== English UI Font =====================
    - family: Manrope
      fonts:
        - asset: assets/fonts/english/Manrope-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/english/Manrope-Light.ttf
          weight: 300
        - asset: assets/fonts/english/Manrope-Regular.ttf
          weight: 400
        - asset: assets/fonts/english/Manrope-Medium.ttf
          weight: 500
        - asset: assets/fonts/english/Manrope-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/english/Manrope-Bold.ttf
          weight: 700
        - asset: assets/fonts/english/Manrope-ExtraBold.ttf
          weight: 800
