// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDD2l35M1ha6MjVKyq2wZkko3SHLnpbIdo',
    appId: '1:291023717996:web:d590653f9ec52b7100fa49',
    messagingSenderId: '291023717996',
    projectId: 'm-mg-f5b70',
    authDomain: 'm-mg-f5b70.firebaseapp.com',
    storageBucket: 'm-mg-f5b70.firebasestorage.app',
    measurementId: 'G-78R5RB1Y6V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDlMh_65tYKcCxcjvPaEhxo4yunGm3dAkU',
    appId: '1:291023717996:android:82a4313377db95d000fa49',
    messagingSenderId: '291023717996',
    projectId: 'm-mg-f5b70',
    storageBucket: 'm-mg-f5b70.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD1-gnhIcoM7Uj48IJnhFhJoOz_6Q7EFQA',
    appId: '1:291023717996:ios:b348763eeb4363d300fa49',
    messagingSenderId: '291023717996',
    projectId: 'm-mg-f5b70',
    storageBucket: 'm-mg-f5b70.firebasestorage.app',
    iosBundleId: 'com.example.twoMProduction',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDD2l35M1ha6MjVKyq2wZkko3SHLnpbIdo',
    appId: '1:291023717996:web:5e54d9ce8babf43c00fa49',
    messagingSenderId: '291023717996',
    projectId: 'm-mg-f5b70',
    authDomain: 'm-mg-f5b70.firebaseapp.com',
    storageBucket: 'm-mg-f5b70.firebasestorage.app',
    measurementId: 'G-K6Y8008BZB',
  );
}
